# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 1
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 5
  TEST_MODEL: True
  SEED_VALUE: 1
  MULTI_PROCESSING_METHOD: forkserver
  HOOKS:
    PERF_STATS:
      MONITOR_PERF_STATS: False
  DATA:
    NUM_DATALOADER_WORKERS: 1
    TRAIN:
      DATA_SOURCES: [disk_filelist]
      DATASET_NAMES: [augsslvoc2012_folder]
#      DATA_SOURCES: [disk_folder]
#      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 4
      TRANSFORMS:
        - name: ImgRotatePil
        - name: RandomResizedCrop
          size: 224
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
    TEST:
      DATA_SOURCES: [disk_filelist]
      DATASET_NAMES: [augsslvoc2012_folder]
#      DATA_SOURCES: [disk_folder]
#      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 4
      TRANSFORMS:
        - name: ImgRotatePil
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1]
  TRAINER:
    TRAIN_STEP_NAME: rot_train_step
  MODEL:
    TRUNK:
      NAME: deeplabv3plus_resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 26
          PRETRAINED: True
          PRETRAINED_PATH: './pretrained_models/'
    HEAD:
      PARAMS: [["glob_pool", {"glob_pool": AdaptiveAvgPool2d}],
               ["mlp", {"dims": [256, 4]}]]
  LOSS:
      name: cross_entropy_multiple_output_single_target
      ignore_index: -1
  OPTIMIZER:
      name: sgd
      weight_decay: 0.0001
      momentum: 0.9
      num_epochs: 1
      nesterov: False
      regularize_bn: False
      regularize_bias: True
      param_schedulers:
        lr:
          name: polynomial
          base_value: 0.1
          num_epochs: 1
          power: 0.9
          update_interval: step
  DISTRIBUTED:
    BACKEND: gloo           # set to "gloo" for cpu only trianing
    NUM_NODES: 1            # no change needed
    NUM_PROC_PER_NODE: 1    # user sets this to number of gpus to use
    INIT_METHOD: tcp        # set to "file" if desired
    RUN_ID: auto            # Set to file_path if using file method. No change needed for tcp and a free port on machine is automatically detected.
  MACHINE:
    DEVICE: cpu
  CHECKPOINT:
    DIR: "./results/rotnet_test"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 1
