# @package _global_
config:
  VERBOSE: False
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_EVERY_NUM_EPOCH: 1
  TEST_MODEL: True
  SEED_VALUE: 1
  MULTI_PROCESSING_METHOD: forkserver
  HOOKS:
    PERF_STATS:
      MONITOR_PERF_STATS: False
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DO_SEMSEG: true
      DATA_SOURCES: [disk_filelist]
      DATASET_NAMES: [augsslvoc2012_folder]
      BATCHSIZE_PER_REPLICA: 8
      TRANSFORMS:
        - name: RandomScalingDense
          min_scale_factor: 0.5
          max_scale_factor: 2.0
          step_size: 0.25
        - name: RandomCropDense
          size: 512
        - name: RandomHorizontalFlipDense
          p: 0.5
        - name: ImgRotatePil
        - name: ToTensorDense
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
    TEST:
      DO_SEMSEG: true
      DATA_SOURCES: [disk_filelist]
      DATASET_NAMES: [augsslvoc2012_folder]
      BATCHSIZE_PER_REPLICA: 8
      TRANSFORMS:
        - name: PadImageDense
          size: 512
        - name: ImgRotatePil
        - name: ToTensorDense
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
  METERS:
    name: accuracy_list_meter
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1]
  TRAINER:
    TRAIN_STEP_NAME: rot_train_step
  MODEL:
    TRUNK:
      NAME: deeplabv3plus_resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 26
          PRETRAINED: True
          PRETRAINED_PATH: './pretrained_models/'
    HEAD:
      PARAMS: [["glob_pool", {"glob_pool": AdaptiveAvgPool2d}],
               ["mlp", {"dims": [256, 4]}]]
  LOSS:
      name: cross_entropy_multiple_output_single_target
      ignore_index: -1
  OPTIMIZER:
      name: sgd
      weight_decay: 0.0001
      momentum: 0.9
      num_epochs: 2
      param_schedulers:
        lr:
          name: polynomial
          base_value: 0.002
          num_epochs: 60
          power: 0.9
          update_interval: step
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: "./results/rotnet_speedtest"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 1
